### ISSUE TITLE
pauseOnHover not working?

### ISSUE THREAD

**Issue by mlncstr** [9bitStudios/flexisel#16]
Any kind of problem you see with the following coffeescript?

$('#home_carousel').flexisel
  visibleItems: 4
  enableResponsiveBreakpoints: true
  autoPlay: true
  autoPlaySpeed: 10000
  pauseOnHover: true
  responsiveBreakpoints:
    portrait:
      changePoint: 2400
      visibleItems: 1

**Comment by polkapox** [comment]
I have a problem, if my PC is offline flexisel is working because manually import the jquery-1.11.1.js and when my pc is online flexisel is not working or showing in my page... i tried also to remove the imported local jquery and import at the ajax/libs/jquery, didnt have luck...

**Comment by 9bitStudios** [comment]
I would stick to downloading a local copy of jQuery and going with that for all scenarios.
