### ISSUE TITLE
Scrolling through the carousel

### ISSUE THREAD

**Issue by connman** [9bitStudios/flexisel#17]
As stated above, when I scroll the carousel, it scrolls one item at a time until the end. Is there anyway when I scroll the carousel, it scrolls three items at a time?

Example:

Item 1 Item 2 Item 3 Item 4 Item 5 Item 6 in the carousel

First three:-
Item 1 Item 2 Item 3

After clicking the next arrow button

Item 4 Item 5 Item 6

Thanks in advance.

**Comment by 9bitStudios** [comment]
Please note that this is now supported with the release of version 2.0.0 and 2.1.0.
