### ISSUE TITLE
can't load at every page..solution please..

### ISSUE THREAD

**Issue by indocutter** [9bitStudios/flexisel#48]
Hi there....

i'm using flexisel at my website http://www.indocutter.com

Problem... at index website ..flexisel is running good...but when i looking at a different page, flexisel does not work...

Solution please...

**Comment by 9bitStudios** [comment]
Hi there -- I don't see Flexisel on this page currently.

**Comment by indocutter** [comment]
Hi there,

please see my website again.. :)

**Comment by 9bitStudios** [comment]
Hi again. It looks like the path to the Flexisel plugin might be wrong on subpages? i.e. the URI on the homepage resolves to this here http://www.indocutter.com/js/jquery.flexisel.js (which works fine) but on subpages resolves to http://www.indocutter.com/categories/Barcode-Label-Printers/js/jquery.flexisel.js (which does not).

**Comment by indocutter** [comment]
What should I do so that the script can be run on any subpages ??

<script type="text/javascript" src="http://code.jquery.com/jquery-1.7.1.min.js"></script>
<script type="text/javascript" src="js/jquery.flexisel.js"></script>

**Comment by 9bitStudios** [comment]
Load it from here http://www.indocutter.com/javascript/..js like you are with other scripts?

**Comment by indocutter** [comment]
I think the problem with the url website www.indocutter.com  , yesterday I change my httacces to rewrite my url. when I delete the script, all goes well.
thank you very much for your help

**Comment by 9bitStudios** [comment]
No problem.
