### ISSUE TITLE
Consider adding tags for the repo.

### ISSUE THREAD

**Issue by Piicksarn** [9bitStudios/flexisel#52]
Hi~
Adding tags for repo could specify points in history and mark release points.
It's helpful for user to know the version and status of repository, and would enable wider distribution of the library, for example on [CDNJS](https://github.com/cdnjs/cdnjs)
Would you please consider on using tags?

Thanks for your great work!!
Piicksarn

**Comment by 9bitStudios** [comment]
Hi there! Thank you for the suggestion. I will take a look at this for future releases.

**Comment by Piicksarn** [comment]
Thank you !:smiley:

**Comment by PeterDaveHello** [comment]
@9bitStudios any possibility to add a tag for it? Since there is request to ask us host it on cdnjs:
https://github.com/cdnjs/cdnjs/issues/5147

**Comment by 9bitStudios** [comment]
v.2.0.0 has a tag/release.  https://github.com/9bitStudios/flexisel/commit/2f4df6eba655d840022e59cb56c48fc82d7a4d2d 

Please let me know if there are any additional steps needed. Thanks!

**Comment by PeterDaveHello** [comment]
Thanks @9bitStudios
