### ISSUE TITLE
Arabic slider creation

### ISSUE THREAD

**Issue by sumeshclt** [9bitStudios/flexisel#53]
How can change slider direction right to left

**Comment by sumeshclt** [comment]
Fix that issue change style.css 
.callbacks_tabs li{ float:right;}

**Comment by 9bitStudios** [comment]
Hey there sumeshclt -- Another thing you can do is change all the instances of scrollLeft and scrollRight inside the plugin to the opposite one. All the scrollLefts become scrollRights and vice versa.
