### ISSUE TITLE
Continuous Scrolling flexisel

### ISSUE THREAD

**Issue by sajiddesigner** [9bitStudios/flexisel#54]
Hello
I want to infinite scrolling flexisel. please let me know how can i do  this. 
My code is

```

 $("#flexiselDemo3").flexisel({
        visibleItems: 3,
        animationSpeed: 1000,
        autoPlay: true,
        autoPlaySpeed: 3000,            
        pauseOnHover: true,
        clone:false,
        enableResponsiveBreakpoints: true,
        responsiveBreakpoints: { 
            portrait: { 
                changePoint:480,
                visibleItems: 1
            }, 
            landscape: { 
                changePoint:640,
                visibleItems: 2
            },
            tablet: { 
                changePoint:768,
                visibleItems: 3
            }
        }
    });

```

**Comment by 9bitStudios** [comment]
Remove clone:false.

**Comment by sajiddesigner** [comment]
Hello,
I tried this but this does not work. It make changes in code which results in layout changes.
see here is what is displayed after removing clone:false

![image](https://cloud.githubusercontent.com/assets/5917783/9568739/7eb804ae-4f6c-11e5-9432-7da37bb89f77.png)

Please provide suitable solutions..
I need to add ad div with clear:both, please tell me how can i restrict div element to be cloned again and again..

**Comment by 9bitStudios** [comment]
You are likely seeing that because the inner div needs to be a bit wider in the CSS which you can increase. How to do this and where is discussed in issue #5. Please let me know if there is anything else that you need.

**Comment by sajiddesigner** [comment]
no. actually i am having following code
     <ul class="flex">
      <li> <img....></li>
      <li> <img....></li>
      <li> <img....></li>
      <li> <img....></li>
      <div class="clearfix"></div>
      </ul>

if i add clone:true then flexisel is clonning entire section inside <ul>

**Comment by 9bitStudios** [comment]
Ah ok. So the clone is happening at the end of the "appendHTML" method

```javascript
if (settings.clone) {
    var cloneContent = object.children().clone();
    object.append(cloneContent);
}
```
You'll need to target it to just clone the list items

```javascript
if (settings.clone) {
    var cloneContent = object.children('li').clone();
    object.append(cloneContent);
}
```

But you will need to keep clone: true to have the infinite scroll. Give that a try and let me know how that works out for you.

**Comment by cordvision** [comment]
Hello
I'm having the same problem. As soon as I add more than 4 pictures, I get "double rows" or sometimes even "triple rows". If I turn clone "off", it only displays a double row when loading the first picture but it's not fixing the issue. Also tried your proposed fix, but had no luck. Here's my test website that exhibits the problem: http://michaeloldhouse.com/AlthausProductions/portfolio.php
Any help is appreciated!

**Comment by 9bitStudios** [comment]
Hi cordvision -- I think you will also need to make the adjustment described in issue #5 I actually made this change in the latest commit as well so if you want to pull the latest that should be in there for you.  Also, for the infinite scrolling you will need to have clone:true. The example provided has clone set to false.

**Comment by 9bitStudios** [comment]
Did this resolve the issue for you?

**Comment by sajiddesigner** [comment]
@9bitStudios i am not using felxisel. Now I am using owl carousel on this project.

Will try flexisel in any other project again and hope this issue is fixed untill then..
