### ISSUE TITLE
want to Highlight a specific image

### ISSUE THREAD

**Issue by arajajyothibabu** [9bitStudios/flexisel#55]
How to show specific image as highlighted on page load?
Please help me out

**Comment by 9bitStudios** [comment]
Hi there -- This is not really supported natively but you could add a class to one of the images and then  add the code to do a highlight visualization in CSS.

**Comment by arajajyothibabu** [comment]
Actually I want to show last image of list upon loading the page.

**Comment by 9bitStudios** [comment]
So yeah, if you use the clone: false option and then add your CSS class to your last image in your unordered list that should do it for you. 

If you do an infinite carousel there is no real concept of a "last image."
