### ISSUE TITLE
Support for navigation of multiple pictures ?

### ISSUE THREAD

**Issue by rishabh1351995** [9bitStudios/flexisel#58]
Hi I used your slider in my website and I was wondering if you guys could add support for multi image navigation  , so that when I click on navigation icon , instead of 1 picture , it bypasses all the picture in current view . so that a person can view all the pics in least amount of time possible.

**Comment by 9bitStudios** [comment]
This is not officially supported but there is discussion on how to modify the slider for this functionality in issue #17

**Comment by 9bitStudios** [comment]
Please note that this is now supported with the release of version 2.0.0.
