### ISSUE TITLE
slider doesn't engage on search

### ISSUE THREAD

**Issue by tsumuel** [9bitStudios/flexisel#59]
If a user searches my page, they get results of query in the carousel. It works if you leave the search box blank and hit enter. If a user enters text and presses enter to search, the carousel disapears or doesn't engage with results at all. 

See page: http://jackpotflash.com/ProfileRate.php

By the way, this plug-in is the star of my project. thanks for creating.

**Comment by tsumuel** [comment]
Thanks anyway. The error was PHP related. Works just fine now.

**Comment by 9bitStudios** [comment]
Glad it worked out. Sorry for the delay in response. New Year's holiday and all that.
