### ISSUE TITLE
flexisel is not a function

### ISSUE THREAD

**Issue by adilogs** [9bitStudios/flexisel#61]
I applied the flexisel and used the flexisel script where I get error

index.html:354 Uncaught TypeError: $(...).flexisel is not a function

**Comment by 9bitStudios** [comment]
Hi there! This is likely because you have included the script for the carousel before you are including jQuery in your page or you are trying to call it before the script is included.

**Comment by adilogs** [comment]
thanks the problem got solved ....

**Comment by kishorpatel85** [comment]
still getting the same error . (I am using MVC framework for my website)

**Comment by 9bitStudios** [comment]
Hi there. I am back from holiday. I apologize for the delay in response. Do you have a demo/dev link available where I can take a look at this?

**Comment by kishorpatel85** [comment]
I solved the error it was a small negligence from my side,
thank you for offering help.
keep the good work going.
