### ISSUE TITLE
Image does not display on chrome browser Version 50.0.2661.94 m

### ISSUE THREAD

**Issue by adilogs** [9bitStudios/flexisel#62]
Images display is hidden however everything shows up in inspect element

![image](https://cloud.githubusercontent.com/assets/16147319/15011183/06b8aab6-120e-11e6-9754-3cd92040adb4.png)

Inspect element screenshot

![image](https://cloud.githubusercontent.com/assets/16147319/15011214/33526864-120e-11e6-969b-07602dbce3fd.png)

**Comment by adilogs** [comment]
this seems to be browser cache related issue as sometimes it displays on browsers. The code needs to be compatible with all versions of browsers.

**Comment by 9bitStudios** [comment]
Hey there. This was an issue of the GitHub page being served over HTTPS, but requested jQuery over HTTP which was blocked by GitHub. I have updated the demo to pull jQuery over HTTPS and it does work in this latest build in Chrome - https://9bitstudios.github.io/flexisel/

**Comment by adilogs** [comment]
do it work in all previous versions of chrome (last year)?

**Comment by adilogs** [comment]
Hey  , I have tried adding jquery script , but still error persists. Please help

**Comment by 9bitStudios** [comment]
Just to confirm, does the demo in the link above work for you?

**Comment by adilogs** [comment]
Yes tried every method , tried to clear cache and hard refresh too.

**Comment by 9bitStudios** [comment]
What does the console say on my demo page here: https://9bitstudios.github.io/flexisel/? I'm really only asking because I am running this same build of Chrome and I'm not seeing the same behavior.

**Comment by adilogs** [comment]
Your web page console Screenshot -

![image](https://cloud.githubusercontent.com/assets/16147319/15104254/1add0e88-15d3-11e6-9095-f65df234e158.png)


My web page screenshot - 


![image](https://cloud.githubusercontent.com/assets/16147319/15104242/e2f19fc0-15d2-11e6-9733-cb50c7fbfa5d.png)

**Comment by adilogs** [comment]
Issue is still there and not solved  , Can you please open this issue?

**Comment by 9bitStudios** [comment]
What I was inquiring about earlier is if the demo page (my demo page) worked for you and from the screen shot it appears that it does. So the issue is not with the browser because the demo page does work for your on your end. That's what I was trying to confirm. So it looks like there is something else going on here. Could you possibly send me a link to your demo so I can take a look and see if you have initialized everything properly? You can just do a <a href="https://jsfiddle.net/">JSFiddle</a> or something like that.

**Comment by adilogs** [comment]
My website link is http://www.hrsummit.in/

**Comment by adilogs** [comment]
The problem is when I put the <li> and <img> tag directly instead of calling from JSON it works fine  , but when I call from JSON it doesn't show up.

Like 

    `<ul id="flexiselDemo3">
       <li><img src="https://s3-ap-southeast-1.amazonaws.com/asiacontent/IHRD.png"></li>
       <li><img src="https://s3-ap-southeast-1.amazonaws.com/asiacontent/hughes.png"></li>
       <li><img src="https://s3-ap-southeast-1.amazonaws.com/asiacontent/neuralIT-logo.png"></li>
       <li><img src="https://s3-ap-southeast-1.amazonaws.com/asiacontent/IFTDO.png"></li>
     </ul>`

When I sue JSON and a js file to call them 

` $.ajax({
          url: "http://s3.amazonaws.com/abc.json",,
          dataType: 'json',
          success: function(results) 
          {
            for(var k=0 ; k<tabsponsors.items.length ; k++)
            {
                spon = tabsponsors.items[k];//Sponsors //
                console.log(spon.image);
                html_str_spon += "<a href="+spon.docLink+" target='_blank'><li><img src="+spon.image+"></li></a>"; 
            }
            $('#flexiselDemo3').append(html_str_spon);
          }
         })`

**Comment by adilogs** [comment]
I found out  , window.load function was causing the problem .Adding  Set timeout function fixed the problem.

**Comment by 9bitStudios** [comment]
Great! Glad that it worked out. Let me know if you run into any other issues. Cheers!
