### ISSUE TITLE
Disable prev/next after completing loop

### ISSUE THREAD

**Issue by mbsankar84** [9bitStudios/flexisel#64]
Want to know in Flexisel how to disable next button after reaching the last child / prev button for first-child?

**Comment by 9bitStudios** [comment]
Hi there -- This occurs automatically if you set the "infinite" setting to false. A class named "disabled" gets added to either arrow when this happens so that this disabled state can be displayed in the UI.

**Comment by mbsankar84** [comment]
HI.,Thanks for reply.I tried it to set infite:false; but its not worked.

**Comment by 9bitStudios** [comment]
You did not display (or link to) your code anywhere after stating "here is my code"

Also, FYI you spelled "infinite" incorrectly. If you do that in code, it definitely will not work.

**Comment by mbsankar84** [comment]
Here is the link I uploaded & tried
http://www.eenadu.net/tv-movie-listings/tv-listings.aspx

**Comment by 9bitStudios** [comment]
So you're using version 1.0.2 of Flexisel in which case you'll want to set clone: false. This was refactored into the "infinite" option for v2.0.0. So either set clone to false in your current implementation or upgrade to version 2 and set infinite to false.

**Comment by mbsankar84** [comment]
Thank you very much.
