### ISSUE TITLE
Element order when set infinitely:true

### ISSUE THREAD

**Issue by vbelbel** [9bitStudios/flexisel#67]
Hi! Thank you for good plugin. 
How i can set element order when option "infinite:true"? 
I need element order from html code.

**Comment by 9bitStudios** [comment]
Right now there is no real concept of element order when infinite is true. But I will keep this issue open because it would probably be useful to have this implemented at some point down the road.

**Comment by dnebeker** [comment]
Similar to this, the first item in the list is not the first item shown.  Basically it's not possible to have an infinite list that presents a logical progression of any kind.

**Comment by 9bitStudios** [comment]
Thank you for the support dnebeker. You have persuaded me to get moving on fixing this. ;) 

This issue should be fixed in the latest commit and release (v.2.2.1). Please let me know if you see any issues with it. I did some cursory testing around it and it looks okay at different widths.

**Comment by 9bitStudios** [comment]
I have decided to close this for now. I believe that the original request can now be achieved by element ordering in the HTML. Please reopen if you encounter any other issues.
