### ISSUE TITLE
Slides. second item overlaps with previous and next one

### ISSUE THREAD

**Issue by HariWebs** [9bitStudios/flexisel#68]
Hi, i am really new to github. when i click the next button. the second item overlaps or shows shadow with first and third. how to solve. issue shows in chrome browser. Thanks in advance

**Comment by 9bitStudios** [comment]
Hi there... Thank you for your input. Do you have a link or screenshot you can provide that gives a bit more detail regarding what you are seeing? It's a little bit unclear as to what "shows shadow" means.

**Comment by HariWebs** [comment]
Its a mistake got found in item max-width. used em instead of px. Thank you for replying...
