### ISSUE TITLE
Need to trigger methods.scroll(true); from page on mouseover event.

### ISSUE THREAD

**Issue by ullasaugustine** [9bitStudios/flexisel#69]
Hi There ,

This plugin is awesome!!

Can we call 'methods.scroll(true)' from our page ?

I found this piece of code from jquery.flexisel.js file , which is used to trigger next /prev scrolls.

 _$(settings.navigationTargetSelector).find(".nbs-flexisel-nav-left").on("click", function (event) {
                    methods.scroll(true);
                });_

I need to call this next/prev function on mouse over when other event happens.

Please help me on this.

Thanks .

Ullas

**Comment by 9bitStudios** [comment]
There is no official hook into calling the internal methods of the plugin but you could easily do something like 

```javascript
$('.nbs-flexisel-nav-left').trigger('click'); 
```

inside of your hover event
