### ISSUE TITLE
visibleItem:1 is not working properly

### ISSUE THREAD

**Issue by rakib32** [9bitStudios/flexisel#71]
If there are more than 5 items with option visibleItem:1 then it's displaying 2 images vertically. Please see the attached image.
```
<li>1</li>
<li>2</li>
<li>3</li>
<li>4</li>
<li>5</li>
<li>6</li>
<li>7</li>
```
![untitled](https://cloud.githubusercontent.com/assets/1880621/21991515/222c9560-dc3d-11e6-84f4-7dde46718494.jpg)

**Comment by 9bitStudios** [comment]
Hi there -- I applied the above steps to repro to the demo package and it appeared to work as expected so there is likely something else going on with your CSS or configuration. Do you perhaps have a demo URL with the issue above that you could point me to where I could take a look? Thanks

**Comment by rakib32** [comment]
Hi, yes it was CSS problem at my end. Now it's working.
