### ISSUE TITLE
Can this flexisel compatible with ie8

### ISSUE THREAD

**Issue by jackiewillen** [9bitStudios/flexisel#72]
I try this on ie8,but cannot work.I dont know how to change the source code.But there is just one error,the addEventListener method or attribution can not be supported.Can you change this.Thank you.

**Comment by jackiewillen** [comment]
I find a solution,
`var isIE=!!window.ActiveXObject;
                var isIE6=isIE&&!window.XMLHttpRequest;
                var isIE8=isIE&&!!document.documentMode;
                var isIE7=isIE&&!isIE6&&!isIE8;

                if(isIE8 || isIE7){
                    object[0].attachEvent('touchmove', methods.touchHandler.handleTouchMove, false);    
//                    li.attachEvent("onclick",function(){
//                        _marker.openInfoWindow(_iw);
//                    })    
                }else{
                    object[0].addEventListener('touchstart', methods.touchHandler.handleTouchStart, false);   
                    
//                    li.addEventListener("click",function(){
//                        _marker.openInfoWindow(_iw);
//                    })
                }
//                object[0].addEventListener('touchstart', methods.touchHandler.handleTouchStart, false);        
//                object[0].addEventListener('touchmove', methods.touchHandler.handleTouchMove, false);         `

**Comment by 9bitStudios** [comment]
Great. I'm glad that worked out.
