### ISSUE TITLE
Can we turn off slider on small widths 

### ISSUE THREAD

**Issue by ullasaugustine** [9bitStudios/flexisel#73]
Thanks for this perfect slider.

Let me ask one question ,

Is there any option to stop slider from working on small widths but we need to make them working on large widths.

Currently I have initialized them on desired widths like page width >750 px .  Is there any other method available like we just set off the slider in small widths.

Thanks in advance.

**Comment by 9bitStudios** [comment]
Hi there-- Sorry for the delay in response. You could just set itemsToScroll to 0 for the widths that you need. Even though this sort of functionality is not officially supported that seems to work for what you are trying to do.

**Comment by 9bitStudios** [comment]
Did this work for you? I am going to close this issue because I believe the solution works for this somewhat unique request and no additional workarounds are needed. Please follow up in this thread if you want to add anything else related to this discussion.

**Comment by ullasaugustine** [comment]
Thanks for the reply. I found another workaround due to my specific requirement. Any how I will test your workaround.

Thanks for the help.
