### ISSUE TITLE
Event Propagation

### ISSUE THREAD

**Issue by wheelix** [9bitStudios/flexisel#75]
I use this to scroll through products to finally get an popup. I think this cathces my click events inside the slider. is it possible to prevent this behaviour?

**Comment by 9bitStudios** [comment]
I am don't know if I am 100% sure what you are encountering and I might need more info or a link to a demo. The carousel does not swallow any click events. As a result, something like the below will work fine...

```javascript
$("#flexiselDemo1").flexisel({
    loaded: function(){
        $("#flexiselDemo1").on("click", "li", function(){
            console.log("click")
        });
    }
});
```
