### ISSUE TITLE
How to disable touch swipe 

### ISSUE THREAD

**Issue by mohdqasim98** [9bitStudios/flexisel#76]
Really like the plugin.
But on mobile devices, currently the slider slides left/right with touch swipe.Is there any way I can disable it so that the slider follows the touch.I mean it should only slide as much the user is dragging his finger on screen.
Also, I am having stuttering issue , with the sliders, is there any way to fix it ?

**Comment by 9bitStudios** [comment]
Hi there -- The easiest way to do this would be to comment out line 192 and 193 in the plugin.
